# Github actions

name: zgled2

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Izpis spremenljivke
        run: echo $GITHUB_WORKSPACE

      - name: Nastavi Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zaženi teste
        run: pytest

      
