# Github actions

name: Github Actions Demo 3

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  push:
    branches: [ main,test ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The build job runs on an ubuntu-latest machine
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Add your steps here
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Izpis spremenljivke
        run: echo $GITHUB_WORKSPACE

      - name: Nastavi Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Zaženi teste
        run: pytest

      
