name: Deljenje podatkov med posli z uporabo artefaktov

on: [push]

jobs:
  posel_1:
    name: Seštej 3 and 7
    runs-on: self-hosted
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > domaca-naloga.txt
      - name: Naloži rezultat za posel 1
        uses: actions/upload-artifact@v4
        with:
          name: naloga_pred
          path: domaca-naloga.txt

  posel_2:
    name: Množi z 9
    needs: posel_1
    runs-on: self-hosted
    steps:
      - name: Prenesi rezultat za posel 1
        uses: actions/download-artifact@v4
        with:
          name: naloga_pred
      - shell: bash
        run: |
          value=`cat domaca-naloga.txt`
          expr $value \* 9 > domaca-naloga.txt
      - name: Naloži rezultat za posel 2
        uses: actions/upload-artifact@v4
        with:
          name: naloga_konec
          path: domaca-naloga.txt

  posel_3:
    name: Prikaži rezultat
    needs: posel_2
    runs-on: self-hosted
    steps:
      - name: Prenesi rezultat za posel 2
        uses: actions/download-artifact@v4
        with:
          name: naloga_konec
      - name: Izpiši končni rezultat
        shell: bash
        run: |
          value=`cat domaca-naloga.txt`
          echo Končni rezultat je $value
