#Github actions demo

name: zgled1

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      - name: Poženemo ukaz v terminalu a one-line script
        run: echo Hello, world!

      - name:  Poženemo večvrstični ukaz v terminalu
        run: |
          echo Prvi ukaz
          echo Drugi ukaz
