#Github actions deploy 

name: zgled5

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPONAME: ${{ secrets.REPO_NAME }}
on:
  workflow_run:
    workflows: ["zgled2"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build_date: ${{ steps.datum.outputs.date }}
    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v2
      
      - name: Prijava v Docker
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Trenutni čas
        id: datum
        run: |
          echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_ENV"
          echo "date=$(date +'%Y-%m-%d--%M-%S')" >> "$GITHUB_OUTPUT"
      
      - name: Zgradi docker sliko
        run: |
          echo ${{ steps.datum.outputs.date }}
          echo "docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date"
          docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPONAME:$date

      - name: Potisni docker sliko
        run: |
          docker push $DOCKER_USERNAME/$REPONAME:$date
  release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Izpis spremenljivke iz drugega joba
        run: echo ${{needs.deploy.outputs.build_date}}

        
