# Github actions

name: Github Actions Matrix Demo

on:
  push:
    branches: [ main,test ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    
    steps:
      
      - uses: actions/checkout@v2

      - name: Izpis spremenljivke
        run: echo $GITHUB_WORKSPACE

      - name: Nastavi Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Zaženi teste
      - name: Zaženi teste
        run: pytest

      
